tap "teamookla/speedtest"
brew "fd"
brew "ffmpegthumbnailer"
brew "fzf"
brew "gh"
brew "ghq"
brew "git"
brew "jq"
brew "llama.cpp"
brew "mas"
brew "mole"
brew "poppler"
brew "python-tk@3.14"
brew "ripgrep"
brew "sevenzip"
brew "tree"
brew "unar"
brew "wget"
brew "yazi"
brew "yt-dlp"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "teamookla/speedtest/speedtest", trusted: true
cask "appcleaner"
cask "claude-code"
cask "flowvision"
cask "ghostty"
cask "keka"
cask "raycast"
cask "rectangle"
cask "sanesidebuttons"
cask "scroll-reverser"
cask "slack"
cask "stats"
cask "viber"
cask "visual-studio-code"
cask "vivaldi"
cask "vlc"
mas "Bitwarden", id: 1352778147
mas "Kindle", id: 302584613
mas "LINE", id: 539883307
mas "Mouse Gestures for Safari", id: 1618804075
mas "wBlock", id: 6746388723
mas "Weather Typing", id: 1402920465
uv "claude-monitor"
